all: cjpp

cjpp: lex.yy.c cjpp.tab.c
	g++ -x c++ -std=gnu++0x lex.yy.c cjpp.tab.c -lfl

cjpp.tab.c: cjpp.y
	win_bison -d cjpp.y

lex.yy.c: cjpp.l
	win_flex cjpp.l

clean:
	-del lex.yy.c cjpp.tab.c cjpp.tab.h a.exe
	echo Cleaned
